content = open("src/pages/Blog.jsx").read() if False else ""
lines = []
lines.append("import { useNavigate } from 'react-router-dom';")
lines.append("import { useEffect, useState } from 'react';")
lines.append("import { client } from '../lib/sanity';")
lines.append("")
lines.append("export default function Blog() {")
lines.append("  const navigate = useNavigate();")
lines.append("  const [posts, setPosts] = useState([]);")
lines.append("  const [loading, setLoading] = useState(true);")
lines.append("")
lines.append("  useEffect(() => {")
lines.append("    client")
lines.append("      .fetch(`*[_type == 'post'] | order(publishedAt desc) { _id, title, slug, publishedAt, excerpt }`)")
lines.append("      .then((data) => { setPosts(data); setLoading(false); })")
lines.append("      .catch(() => setLoading(false));")
lines.append("  }, []);")
lines.append("")
lines.append("  return (")
lines.append("    <div style={{ background: '#C8BFB0', minHeight: '100vh', padding: '14px', fontFamily: 'Inter, sans-serif' }}>")
lines.append("      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>")
lines.append("        <button onClick={() => navigate('/')} style={{ display: 'inline-flex', alignItems: 'center', gap: 8, fontSize: 16, color: '#3a3430', background: '#F5F0E8', border: 'none', borderRadius: 40, padding: '10px 24px', cursor: 'pointer', fontFamily: 'Inter, sans-serif', fontWeight: 500 }}>")
lines.append("          \u2190 Home")
lines.append("        </button>")
lines.append("        <a href='https://kaavyaindhu.sanity.studio' target='_blank' rel='noreferrer'")
lines.append("          style={{ display: 'inline-flex', alignItems: 'center', gap: 6, fontSize: 14, color: '#c4a0b0', background: '#F5F0E8', border: '1px dashed #E8729A', borderRadius: 40, padding: '8px 20px', fontFamily: 'Caveat, cursive', textDecoration: 'none', opacity: 0.75 }}>")
lines.append("          + write a post")
lines.append("        </a>")
lines.append("      </div>")
lines.append("      <h1 style={{ fontFamily: 'DM Serif Display, serif', fontSize: 'clamp(52px, 9vw, 80px)', color: '#E8729A', lineHeight: 1, margin: 0 }}>My Blog</h1>")
lines.append("      <p style={{ fontFamily: 'Caveat, cursive', fontSize: 28, color: '#9a9285', margin: '6px 0 28px' }}>thoughts and writing</p>")
lines.append("      {loading && (<div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: 300 }}><p style={{ fontFamily: 'Caveat, cursive', fontSize: 24, color: '#9a9285' }}>loading posts...</p></div>)}")
lines.append("      {!loading && posts.length === 0 && (")
lines.append("        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', minHeight: 300, textAlign: 'center' }}>")
lines.append("          <svg width='180' height='160' viewBox='0 0 180 160' fill='none'>")
lines.append("            <path d='M90 130 C90 130 20 90 20 50 C20 28 36 14 54 14 C65 14 75 20 81 30 C87 20 97 14 108 14 C126 14 142 28 142 50 C142 90 90 130 90 130 Z' fill='#f5d4e0' stroke='#E8729A' strokeWidth='2'/>")
lines.append("            <path d='M90 118 C90 118 32 82 32 50 C32 34 44 26 54 26 C63 26 71 32 77 42' stroke='#E8729A' strokeWidth='1.4' fill='none' strokeLinecap='round' opacity='0.4'/>")
lines.append("          </svg>")
lines.append("          <p style={{ fontFamily: 'DM Serif Display, serif', fontSize: 42, color: '#E8729A', margin: '20px 0 0' }}>coming soon</p>")
lines.append("          <p style={{ fontFamily: 'Caveat, cursive', fontSize: 28, color: '#9a9285', margin: '8px 0 0' }}>I\u2019m writing \u2665</p>")
lines.append("          <p style={{ fontSize: 17, color: '#7a6e68', lineHeight: 1.8, maxWidth: 420, margin: '20px auto 0' }}>This space will be home to my thoughts, life lessons, and personal stories. Check back soon.</p>")
lines.append("        </div>")
lines.append("      )}")
lines.append("      {!loading && posts.length > 0 && (")
lines.append("        <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>")
lines.append("          {posts.map((post, idx) => {")
lines.append("            const colors = [")
lines.append("              { bg: '#F5F0E8', title: '#3a3430', date: '#b0a898', text: '#5a5248', accent: '#E8729A' },")
lines.append("              { bg: '#EDE0E8', title: '#5a2a42', date: '#b888a4', text: '#6a3a52', accent: '#8a3455' },")
lines.append("              { bg: '#D9EDE6', title: '#1a4a38', date: '#5a9e86', text: '#2a5a48', accent: '#1a5040' },")
lines.append("              { bg: '#F5EDD8', title: '#5a3a10', date: '#c4956a', text: '#6a4a20', accent: '#7a4f10' },")
lines.append("              { bg: '#E8E0F0', title: '#3a1a5a', date: '#9070c0', text: '#4a2a6a', accent: '#4a2070' },")
lines.append("            ];")
lines.append("            const c = colors[idx % colors.length];")
lines.append("            const date = post.publishedAt ? new Date(post.publishedAt).toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' }) : '';")
lines.append("            return (")
lines.append("              <div key={post._id} style={{ background: c.bg, borderRadius: 14, padding: '36px 44px', position: 'relative', overflow: 'hidden' }}>")
lines.append("                <p style={{ fontFamily: 'Caveat, cursive', fontSize: 15, color: c.date, letterSpacing: 1, textTransform: 'uppercase', margin: '0 0 8px' }}>{date}</p>")
lines.append("                <h2 style={{ fontFamily: 'DM Serif Display, serif', fontSize: 38, color: c.title, margin: '0 0 16px', lineHeight: 1.1 }}>{post.title}</h2>")
lines.append("                {post.excerpt && <p style={{ fontSize: 17, color: c.text, lineHeight: 1.85, maxWidth: 680, margin: '0 0 20px' }}>{post.excerpt}</p>}")
lines.append("                <div style={{ display: 'inline-flex', alignItems: 'center', gap: 8, fontSize: 14, fontWeight: 500, background: c.accent, color: '#fff', borderRadius: 40, padding: '8px 20px' }}>")
lines.append("                  read more \u2192")
lines.append("                </div>")
lines.append("              </div>")
lines.append("            );")
lines.append("          })}")
lines.append("        </div>")
lines.append("      )}")
lines.append("    </div>")
lines.append("  );")
lines.append("}")

with open("src/pages/Blog.jsx", "w") as f:
    f.write("\n".join(lines))
print("Blog.jsx updated!")
